FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    ffmpeg libsm6 libxext6 libxrender-dev libgl1-mesa-glx libglib2.0-0 \
    python3-opencv git curl wget unzip \
    && apt-get clean

RUN pip install --upgrade pip && pip install jupyterlab

WORKDIR /workspace

COPY requirements.txt /workspace/requirements.txt
RUN pip install -r /workspace/requirements.txt

RUN apt-get update && apt-get install -y \
    libgtk2.0-dev libgl1-mesa-glx libglib2.0-0


EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

#docker build -f Dockerfile_cpu -t wholebody-pose-cpu .

#docker run --name wholebody-windows-cpu -v %cd%:/workspace -p 8888:8888 -it wholebody-pose-cpu
#docker run --cpus=8 --memory=20g --name wholebody-windows-cpu -v %cd%:/workspace -p 8888:8888 -it wholebody-pose-cpu
#docker run --name wholebody-windows-cpu -v %cd%:/workspace -e DISPLAY=host.docker.internal:0.0 --cpus=8 --memory=20g -p 8888:8888 -it wholebody-pose-cpu

#docker start -ai wholebody-windows-cpu
